services:
  backend:
    build: ./flask-server
    container_name: plagexit-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - FRONTEND_URLS=http://localhost
      - BACKEND_URL=http://backend:5000
    volumes:
      - ./flask-server/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./client
    container_name: plagexit-frontend
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

# Using MongoDB Atlas for database
# Make sure to create .env file from env.example before running 